In [1]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [9]:
def create_array(array_size = (2, 2)):
    return np.zeros_like([0],shape=array_size)

#print(create_array((3, 2, 3)))
#print(type(create_array((3, 2, 3))))

<class 'numpy.ndarray'>


In [ ]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [14]:
def set_one(input_array):
    np.fill_diagonal(a=input_array, val=1)
    return input_array

#print(set_one(np.array([[1,2],[3,4]])))


[[1 2]
 [3 1]]


In [ ]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 3], [2, 4]]
# do_transpose()

In [15]:
def do_transpose(input_array):
    return np.transpose(input_array)

#print(do_transpose(np.array([[1,2],[3,4]])))

[[1 3]
 [2 4]]


In [ ]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 2
# Ki: [0.12, 0.17]
# round_array()

In [21]:
def round_array(input_array, n = 2):
    return np.around(input_array, n)

#print(round_array(np.array([0.1223, 0.1675]), 3))

[0.122 0.168]


In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [22]:
def bool_array(input_array):
    return input_array.astype(bool)

#print(bool_array(np.array([[1, 0, 0], [1, 1, 1],[0, 0, 0]])))

[[ True False False]
 [ True  True  True]
 [False False False]]


In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ False True True], [ False  False  False], [True True True]]
# invert_bool_array()

In [23]:
def invert_bool_array(input_array):
    return np.invert(input_array.astype(bool))

#print(invert_bool_array(np.array([[1, 0, 0], [1, 1, 1],[0, 0, 0]])))

[[False  True  True]
 [False False False]
 [ True  True  True]]


In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


In [25]:
def flatten(input_array):
    return input_array.reshape(-1)

#print(flatten(np.array([[1,2], [3,4]])))

[1 2 3 4]
